/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sk_baka_android_spi_AndroidFS */

#ifndef _Included_sk_baka_android_spi_AndroidFS
#define _Included_sk_baka_android_spi_AndroidFS
#ifdef __cplusplus
extern "C" {
#endif
#undef sk_baka_android_spi_AndroidFS_EXDEV
#define sk_baka_android_spi_AndroidFS_EXDEV 18L
/*
 * Class:     sk_baka_android_spi_AndroidFS
 * Method:    deleteInt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sk_baka_android_spi_AndroidFS_deleteInt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sk_baka_android_spi_AndroidFS
 * Method:    mkdirInt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sk_baka_android_spi_AndroidFS_mkdirInt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sk_baka_android_spi_AndroidFS
 * Method:    mkdirInt2
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_sk_baka_android_spi_AndroidFS_mkdirInt2
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     sk_baka_android_spi_AndroidFS
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sk_baka_android_spi_AndroidFS_strerror
  (JNIEnv *, jobject, jint);

/*
 * Class:     sk_baka_android_spi_AndroidFS
 * Method:    getmod
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sk_baka_android_spi_AndroidFS_getmod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sk_baka_android_spi_AndroidFS
 * Method:    rename
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sk_baka_android_spi_AndroidFS_rename
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
