/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sk_baka_android_DirUtils */

#ifndef _Included_sk_baka_android_DirUtils
#define _Included_sk_baka_android_DirUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sk_baka_android_DirUtils
 * Method:    mkdirInt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sk_baka_android_DirUtils_mkdirInt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sk_baka_android_DirUtils
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sk_baka_android_DirUtils_strerror
  (JNIEnv *, jobject, jint);

/*
 * Class:     sk_baka_android_DirUtils
 * Method:    deleteInt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sk_baka_android_DirUtils_deleteInt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
